### ISSUE TITLE
Cannot connect to V2 staging net

### ISSUE THREAD

**Issue by felipeclopes** [XRPL-Labs/XrplTxData#2]
There is an error when connecting to `Testnet v2` https://xumm.notion.site/Hooks-V2-staging-net-info-XLS20-518fa261c5cd49d2bcb89a5b9e7bef05

The flag `AllowNoFullHistory` does not impact the connection, so I assume the TxData could not connect to the WebSocket provided.

``` typescript
const txd = new TxData(["wss://hooks-testnet-v2.xrpl-labs.com"], {
	AllowNoFullHistory: false,
});

txd.get("<transaction>");
```

Error:

```
Uncaught (in promise) ALL_CONNECTIONS_FAILED: All endpoints are offline (or don't provide full history)
    at TxData.GenerateError (webpack-internal:///./node_modules/xrpl-txdata/dist/src/index.js:282:19)
    at TxData.eval (webpack-internal:///./node_modules/xrpl-txdata/dist/src/index.js:248:33)
    at Generator.next (<anonymous>)
    at fulfilled (webpack-internal:///./node_modules/xrpl-txdata/dist/src/index.js:6:58)
```

Is there anything I'm missing?

**Comment by WietseWind** [comment]
When connecting to the Hooks V2 testnet, Full History must _not_ be requested, so `AllowNoFullHistory` must be true. The lib. will be searching for mainnet full history, and Hooks V2 testnet is a different net, it can't satisfy the mainnet FH needs.
